"use client";
import { useEffect, useMemo, useState } from "react";
import { PLAYERS, adena, contributionTotal, crystalLedger, cycleFund, initialData, recipientBalance, type AppData, type GearCycle, type Player } from "./lib/model";

type History = { id:number; action:string; actor:string; summary:string; createdAt:string };
const uid = () => crypto.randomUUID();
const today = () => new Date().toISOString().slice(0, 10);
export default function Dashboard() {
  const [data, setData] = useState<AppData>(initialData); const [version, setVersion] = useState(0); const [admin, setAdmin] = useState(false);
  const [history, setHistory] = useState<History[]>([]); const [tab, setTab] = useState<"gear"|"crystal"|"history">("gear");
  const [panel, setPanel] = useState(false); const [notice, setNotice] = useState(""); const ledger = useMemo(() => crystalLedger(data), [data]);
  async function load(){ const r=await fetch("/api/state",{cache:"no-store"}); const j=await r.json(); setData(j.data); setVersion(j.version); setHistory(j.history); setAdmin(j.admin); }
  // The first request hydrates the public snapshot from durable storage.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{void load();},[]);
  async function save(next:AppData, action:string, summary:string){ setNotice("Salvando…"); const r=await fetch("/api/state",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({data:next,version,action,summary})}); const j=await r.json(); if(!r.ok){setNotice(j.error);return false;} setData(next);setVersion(j.version);setNotice("Salvo com segurança.");await load();return true; }
  function addCycle(fd:FormData){ const item=String(fd.get("item")||"").trim(), value=Number(fd.get("value")); const next:AppData={...data,cycles:[...data.cycles,{id:uid(),item,value,status:"active",recipients:PLAYERS.map(player=>({player,received:false,contributions:[]}))}]}; save(next,"Novo item",`${item} • ${adena(value)} Adena`); }
  function addContribution(fd:FormData){ const cycleId=String(fd.get("cycle")), player=String(fd.get("player")) as Player, amount=Number(fd.get("amount")), at=String(fd.get("at")), note=String(fd.get("note")||""); const next=structuredClone(data); const r=next.cycles.find(c=>c.id===cycleId)!.recipients.find(x=>x.player===player)!; r.contributions.push({id:uid(),player,amount,at,note}); save(next,"Contribuição",`${player} contribuiu ${adena(amount)} Adena`); }
  function receive(c:GearCycle, player:Player){ const ix=c.recipients.findIndex(r=>r.player===player), nextIx=c.recipients.findIndex(r=>!r.received); if(ix!==nextIx){setNotice("Respeite a ordem dos turnos antes de confirmar o recebimento.");return;} if(cycleFund(c)<c.value){setNotice(`Faltam ${adena(c.value-cycleFund(c))} Adena no caixa para este item.`);return;} const next=structuredClone(data); const nc=next.cycles.find(x=>x.id===c.id)!; const r=nc.recipients[ix];r.received=true;r.receivedAt=today(); if(nc.recipients.every(x=>x.received)) nc.status="complete"; save(next,"Item entregue",`${player} recebeu ${c.item}`); }
  function moveRecipient(cycleId:string,index:number,delta:number){const next=structuredClone(data);const cycle=next.cycles.find(c=>c.id===cycleId)!;const target=index+delta;const firstPending=cycle.recipients.findIndex(r=>!r.received);if(index<firstPending||target<firstPending||target<0||target>=cycle.recipients.length)return;const player=cycle.recipients[index].player;[cycle.recipients[index],cycle.recipients[target]]=[cycle.recipients[target],cycle.recipients[index]];save(next,"Fila reorganizada",`${player} mudou de posição em ${cycle.item}`);}
  function addDrop(fd:FormData){const item=String(fd.get("item")||""),crystals=Number(fd.get("crystals")),keeper=(String(fd.get("keeper")||"")||null) as Player|null,note=String(fd.get("note")||"");const next={...data,drops:[...data.drops,{id:uid(),at:String(fd.get("at")),item,crystals,keeper,note}]};save(next,"Drop registrado",keeper?`${keeper} ficou com ${item} (${crystals} cristais)`:`${item} virou ${crystals} cristais`);}
  function addPayment(fd:FormData){const crystals=Number(fd.get("crystals")),note=String(fd.get("note")||"");const next={...data,crystalPayments:[...data.crystalPayments,{id:uid(),at:String(fd.get("at")),crystals,note}]};save(next,"Distribuição",`${crystals} cristais compensados entre os saldos`);}
  const current=data.cycles.find(c=>c.status==="active")||data.cycles.at(-1);
  return <main>
    <header><div className="brand"><div className="crest">P</div><div><p>LINEAGE II • LU4</p><h1>ParabelluM</h1></div></div><div className="status"><span></span>Visão pública atualizada</div></header>
    <section className="hero"><div><span className="eyebrow">TESOURARIA DA CP</span><h2>Força coletiva.<br/><em>Progresso justo.</em></h2><p>Acompanhe cada Adena, equipamento e cristal com transparência para os cinco membros da CP.</p></div>{current&&<div className="hero-card"><small>OBJETIVO ATUAL</small><strong>{current.item}</strong><div className="bar"><i style={{width:`${Math.min(100,cycleFund(current)/current.value*100)}%`}}/></div><b>{adena(cycleFund(current))} <small>/ {adena(current.value)} Adena</small></b><span>{current.recipients.filter(r=>r.received).length}/5 equipados</span></div>}</section>
    <nav><button className={tab==="gear"?"active":""} onClick={()=>setTab("gear")}>⚔ Equipamentos</button><button className={tab==="crystal"?"active":""} onClick={()=>setTab("crystal")}>◆ Cristais & Drops</button><button className={tab==="history"?"active":""} onClick={()=>setTab("history")}>◷ Histórico</button></nav>
    {tab==="gear"&&<section className="content"><div className="section-title"><div><span>CICLOS DE EQUIPAMENTO</span><h3>Fundo compartilhado de Adena</h3></div><p>Contribuições formam o caixa. Cada entrega desconta o valor do item e gera o saldo individual.</p></div><div className="cycles">{data.cycles.map(c=><article className="cycle" key={c.id}><div className="cycle-head"><div><span className={c.status}>{c.status==="active"?"EM ANDAMENTO":"CONCLUÍDO"}</span><h4>{c.item}</h4><small>{adena(c.value)} Adena por jogador</small></div><div className="fund"><small>CAIXA DISPONÍVEL</small><strong>{adena(cycleFund(c))}</strong></div></div><div className="player-grid">{c.recipients.map((r,i)=>{const bal=recipientBalance(r,c.value);return <div className={`player ${r.received?"received":""}`} key={r.player}><b className="turn">{i+1}</b><div className="avatar">{r.player[0]}</div><strong>{r.player}</strong><small>{r.received?"Item recebido":i===c.recipients.findIndex(x=>!x.received)?"Próximo da fila":"Aguardando turno"}</small><div className="numbers"><span>Contribuiu <b>{adena(contributionTotal(r))}</b></span><span>Saldo <b className={bal<0?"debt":"credit"}>{bal<0?`-${adena(-bal)}`:`+${adena(bal)}`}</b></span></div>{admin&&!r.received&&i===c.recipients.findIndex(x=>!x.received)&&<button className="receive" onClick={()=>receive(c,r.player)}>Confirmar entrega</button>}</div>})}</div></article>)}</div></section>}
    {tab==="crystal"&&<section className="content"><div className="section-title"><div><span>ACERTO DE DROPS</span><h3>Livro-razão de cristais D</h3></div><p>Itens mantidos viram dívida; futuras distribuições compensam automaticamente quem tem crédito.</p></div><div className="ledger">{PLAYERS.map(p=><div className="ledger-card" key={p}><div className="avatar">{p[0]}</div><b>{p}</b><strong className={ledger[p]<0?"debt":"credit"}>{ledger[p]<0?"Deve":"A receber"} {Math.abs(ledger[p]).toFixed(1)}</strong><small>cristais D</small></div>)}</div><div className="events"><h4>Últimos movimentos</h4>{[...data.drops].reverse().map(d=><div className="event" key={d.id}><span>◆</span><div><b>{d.item}</b><small>{d.at} · {d.keeper?`${d.keeper} manteve o item`:"Convertido para o grupo"}</small></div><strong>{d.crystals} D</strong></div>)}{!data.drops.length&&<p className="empty">Nenhum drop registrado ainda.</p>}</div></section>}
    {tab==="history"&&<section className="content"><div className="section-title"><div><span>AUDITORIA</span><h3>Histórico imutável</h3></div><p>Cada salvamento registra autor, horário e resumo da mudança.</p></div><div className="history">{history.map(h=><div key={h.id}><span>◷</span><div><b>{h.action}</b><p>{h.summary}</p><small>{new Date(h.createdAt).toLocaleString("pt-BR")} · {h.actor}</small></div></div>)}{!history.length&&<p className="empty">O histórico começa no primeiro lançamento.</p>}</div></section>}
    <footer><b>PARABELLUM</b><span>5 guerreiros · 1 objetivo</span><small>Dados públicos em modo somente leitura</small></footer>
    <button className="admin-fab" onClick={()=>admin?setPanel(!panel):location.href="/signin-with-chatgpt?return_to=%2F"}>{admin?"⚙ Admin":"♜ Admin"}</button>
    {panel&&admin&&<aside className="admin-panel"><button className="close" onClick={()=>setPanel(false)}>×</button><span>CONTROLE DO LÍDER</span><h3>Novo lançamento</h3>{notice&&<p className="notice">{notice}</p>}<details open><summary>Contribuição de Adena</summary><form action={addContribution}><label>Item<select name="cycle">{data.cycles.filter(c=>c.status==="active").map(c=><option value={c.id} key={c.id}>{c.item}</option>)}</select></label><label>Jogador<select name="player">{PLAYERS.map(p=><option key={p}>{p}</option>)}</select></label><div className="row"><label>Valor<input name="amount" type="number" min="1" step="1" required/></label><label>Data<input name="at" type="date" defaultValue={today()} required/></label></div><label>Observação<input name="note" maxLength={120}/></label><button>Registrar Adena</button></form></details><details><summary>Ordem de recebimento</summary><div className="order-list">{data.cycles.filter(c=>c.status==="active").map(c=><div className="order-cycle" key={c.id}><b>{c.item}</b>{c.recipients.map((r,i)=>{const first=c.recipients.findIndex(x=>!x.received);return <div className={r.received?"locked":""} key={r.player}><span><i>{i+1}</i>{r.player}{r.received&&<small>recebido</small>}</span><span><button type="button" aria-label={`Subir ${r.player}`} disabled={r.received||i<=first} onClick={()=>moveRecipient(c.id,i,-1)}>↑</button><button type="button" aria-label={`Descer ${r.player}`} disabled={r.received||i===c.recipients.length-1} onClick={()=>moveRecipient(c.id,i,1)}>↓</button></span></div>})}</div>)}</div></details><details><summary>Novo item / ciclo</summary><form action={addCycle}><label>Nome do item<input name="item" required/></label><label>Valor por jogador<input name="value" type="number" min="1" step="1" required/></label><button>Criar ciclo</button></form></details><details><summary>Drop ou item mantido</summary><form action={addDrop}><label>Item<input name="item" required/></label><div className="row"><label>Cristais D<input name="crystals" type="number" min="1" step="1" required/></label><label>Data<input name="at" type="date" defaultValue={today()} required/></label></div><label>Quem ficou<select name="keeper"><option value="">Ninguém — cristalizar</option>{PLAYERS.map(p=><option key={p}>{p}</option>)}</select></label><label>Observação<input name="note"/></label><button>Registrar drop</button></form></details><details><summary>Distribuir cristais</summary><form action={addPayment}><div className="row"><label>Quantidade<input name="crystals" type="number" min="1" step="1" required/></label><label>Data<input name="at" type="date" defaultValue={today()} required/></label></div><label>Observação<input name="note"/></label><button>Compensar saldos</button></form></details><a className="logout" href="/signout-with-chatgpt?return_to=%2F">Sair do modo Admin</a></aside>}
  </main>;
}
